MODULE-2
reviakin/reviakin-node_mentoring_program_global_2021_q3 pull request #1
Opened 2021-10-27 14:30 UTC by reviakin

2021-10-29 16:08 UTC, Kuznietsov requested changes

2021-10-29 16:08 UTC, Kuznietsov commented on src/task2/index.ts
> +readStream.pipe(csvtojson()).pipe(writeStream);
Could you, please, look at the format of the input and the output at the example carefully. They have some differences and you need to implement the code to produce such an output.

2021-10-29 16:08 UTC, Kuznietsov commented on .gitignore
> +src/task2/txt/**
Could you, please, add the rule for excluding `csv` files too.

2021-11-01 12:36 UTC, reviakin commented on .gitignore
> +src/task2/txt/**
@Kunzetsov the file was updated

2021-11-01 12:43 UTC, reviakin commented on src/task2/index.ts
> +readStream.pipe(csvtojson()).pipe(writeStream);
@Kunzetsov, Should content from the "txt" file have a valid JSON structure?

2021-11-01 13:45 UTC, reviakin commented on src/task2/index.ts
> +readStream.pipe(csvtojson()).pipe(writeStream);
Added PreFileLine callback to make a table's headers to lower case

2021-11-02 06:44 UTC, Kunzetsov approved these changes
Code LGTM. Good job 👍

2021-11-03 15:58 UTC, merged